### ISSUE TITLE
[Performance] Blockspan Page takes alot of time to open and hence is un-demoable

### ISSUE THREAD

**Issue by girish-velas** [dambaev/op-energy#142]
### Description

Blockspan Page takes alot of time to open and hence is un-demoable.
E.g. - http://dev-exchange.op-energy.info/signet/tetris/blockspans/1

### Problem to be solved

Performance is really slow

### Proposed solution

No solution yet

#### Additional info

one observation

this page, energy summary, past

http://dev-exchange.op-energy.info/signet/tetris/energy_summary/000000df2ab7d0d7893c9129a775345c10f8a7279037e295dd992273236d0067/0000005f8f8f0567d38ae74cc4a7e2a0e4135b49262c1158620b9a5bdc481c55

renders snappy. and the blockspans in theory at least is just 11 of these summaries. (plus the future span.)

the future span is this

http://dev-exchange.op-energy.info/signet/tetris/energy_summary/000000df2ab7d0d7893c9129a775345c10f8a7279037e295dd992273236d0067/120000

which also renders fast.

**Comment by dambaev** [comment]
I guess, that now this URL is http://dev-exchange.op-energy.info/signet/hashstrikes/blockspans/1 and this issue had been 
fixed by b84c5cc4ddc671ba58c5bb3090efdc63f773bb55 commit
