### ISSUE TITLE
[Performance] Use of caching for all block stats which are 6 blocks deep from the tip

### ISSUE THREAD

**Issue by girish-velas** [dambaev/op-energy#147]
### Description

Currently we are calculating all block stats for blockspans but its not necessary to do so and instead we can cache them in db and use that instead of querying the blockchain ( which is slower then the DB ).

### Problem to be solved

Performance

### Proposed solution

Cache the stats in DB

**Comment by girish-velas** [comment]
More details to come

**Comment by Natsvora** [comment]
This task is done and working moving to done
