### ISSUE TITLE
[Feature] New statistics in energy detail view page

### ISSUE THREAD

**Issue by girish-velas** [dambaev/op-energy#175]
### Description

Implement New statics for energy detail view

<img width="1042" alt="Screenshot 2022-09-29 at 9 53 13 PM" src="https://user-images.githubusercontent.com/104083995/193086135-4811138f-0a82-40f9-a618-9478dd8e17ac.png">

From the image the 
- avg for x blocks
- std for x blocks
- NBDR rate for x blocks

These are the statics that could allow users to make decisions

### Problem to be solved

Providing more statistics to the user

### Proposed solution

- Implement a new api endpoint that exposes these details based on blockspan provided

**Comment by Natsvora** [comment]
![image](https://user-images.githubusercontent.com/24829422/215410074-209669ab-77b2-4efd-8e40-fabebf61ec0c.png)
Changes are deployed into exchange. Now waiting for confirmation from thomas before closing this issue

**Comment by Natsvora** [comment]
It is verified and test in exchange, moving this task to done
